# Generated by Django 5.2.17 on 2026-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used as the category id in API responses.', unique=True)),
                ('summary', models.TextField(help_text='Plain-English explanation of what this usually means.')),
                ('next_step', models.TextField(help_text='The single clear next action for this category.')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated words/phrases used to match free-text enquiries to this category.')),
                ('guide_link', models.URLField(blank=True, help_text='Link to the full LEASE guidance page, if there is one.')),
                ('is_urgent', models.BooleanField(default=False, help_text='Flag urgent categories (e.g. forfeiture threats).')),
            ],
            options={
                'verbose_name': 'Enquiry category',
                'verbose_name_plural': 'Enquiry categories',
                'ordering': ['name'],
            },
        ),
    ]
