# Generated by Django 5.2.17 on 2026-08-28 09:52

from django.db import migrations

LEASE_GUIDE_BASE = "https://www.lease-advice.org/advice-guide"

CATEGORIES = [
    {
        "slug": "service-charges",
        "name": "Service charges",
        "summary": (
            "This usually means a dispute or question about charges your landlord or "
            "managing agent has asked you to pay towards running or maintaining the "
            "building."
        ),
        "next_step": (
            "Read our guide to service charges to understand what you can and can't "
            "be charged for, then get in touch if you still have questions."
        ),
        "keywords": (
            "service charge, service charges, invoice, maintenance fee, management "
            "fee, unreasonable charge, bill from landlord"
        ),
        "guide_link": f"{LEASE_GUIDE_BASE}/costs-and-charges/service-charges/",
        "is_urgent": False,
    },
    {
        "slug": "ground-rent",
        "name": "Ground rent",
        "summary": (
            "This usually means a question about the ground rent your lease requires "
            "you to pay, including how much it is or whether it can increase."
        ),
        "next_step": (
            "Read our guide to ground rent to check what your lease allows, then get "
            "in touch if it's still unclear."
        ),
        "keywords": "ground rent, rent increase, doubling clause, peppercorn rent",
        "guide_link": f"{LEASE_GUIDE_BASE}/costs-and-charges/ground-rent/",
        "is_urgent": False,
    },
    {
        "slug": "major-works-section-20",
        "name": "Major works / Section 20 consultation",
        "summary": (
            "This usually means your landlord is planning, or has done, major "
            "building work and you're unsure about the consultation process or costs."
        ),
        "next_step": (
            "Read our guide to Section 20 consultation to understand your rights "
            "during major works, then get in touch if you have concerns."
        ),
        "keywords": (
            "major works, section 20, s20, consultation, building work, scaffolding, "
            "roof repair costs"
        ),
        "guide_link": f"{LEASE_GUIDE_BASE}/costs-and-charges/section-20-consultation/",
        "is_urgent": False,
    },
    {
        "slug": "lease-extension",
        "name": "Lease extension",
        "summary": (
            "This usually means you want to extend the number of years left on your "
            "lease, or you're unsure how the process works."
        ),
        "next_step": (
            "Read our guide to lease extension to understand the process and costs, "
            "then get in touch to talk through your options."
        ),
        "keywords": "extend lease, lease extension, short lease, years remaining, premium",
        "guide_link": f"{LEASE_GUIDE_BASE}/lease-extension/",
        "is_urgent": False,
    },
    {
        "slug": "right-to-manage",
        "name": "Right to manage",
        "summary": (
            "This usually means you and other leaseholders want to take over "
            "managing the building yourselves, without needing to buy the freehold."
        ),
        "next_step": (
            "Read our guide to Right to Manage to see if you're eligible and what's "
            "involved, then get in touch if you'd like support."
        ),
        "keywords": "right to manage, rtm, take over management, managing agent problem",
        "guide_link": f"{LEASE_GUIDE_BASE}/building-management/right-to-manage/",
        "is_urgent": False,
    },
    {
        "slug": "repairs-and-maintenance",
        "name": "Repairs and maintenance",
        "summary": (
            "This usually means a disagreement about who is responsible for repairs "
            "or maintenance to the building or your flat."
        ),
        "next_step": (
            "Read our guide to repairs and maintenance to check what your lease "
            "says, then get in touch if the issue isn't being resolved."
        ),
        "keywords": "repairs, maintenance, leak, damp, disrepair, communal area, not fixed",
        "guide_link": f"{LEASE_GUIDE_BASE}/building-management/repairs/",
        "is_urgent": False,
    },
    {
        "slug": "breach-of-lease-forfeiture",
        "name": "Breaching your lease / forfeiture threat",
        "summary": (
            "This usually means your landlord says you've broken a condition of "
            "your lease, and may be threatening to take back your home."
        ),
        "next_step": (
            "This can be urgent — read our guide on breach of lease and forfeiture "
            "now, and speak to an adviser as soon as possible."
        ),
        "keywords": (
            "forfeiture, breach of lease, broken lease terms, repossess, court "
            "threat, section 146"
        ),
        "guide_link": (
            f"{LEASE_GUIDE_BASE}/disputes/breaching-your-lease-and-forfeiture/"
        ),
        "is_urgent": True,
    },
    {
        "slug": "not-sure",
        "name": "Not sure / something else",
        "summary": (
            "We couldn't confidently match your situation to one of our categories, "
            "or you've told us you're not sure."
        ),
        "next_step": (
            "Speak to one of our advisers, who can help you work out what's going "
            "on and what to do next."
        ),
        "keywords": "",
        "guide_link": "",
        "is_urgent": False,
    },
]


def seed_categories(apps, schema_editor):
    EnquiryCategory = apps.get_model("api", "EnquiryCategory")
    for category in CATEGORIES:
        EnquiryCategory.objects.update_or_create(
            slug=category["slug"], defaults=category
        )


def remove_categories(apps, schema_editor):
    EnquiryCategory = apps.get_model("api", "EnquiryCategory")
    EnquiryCategory.objects.filter(
        slug__in=[category["slug"] for category in CATEGORIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
